// <auto-generated />
using System;
using Asientos.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Asientos.Infraestructura.Migrations
{
    [DbContext(typeof(AsientosDbContext))]
    [Migration("20260107233618_AddUsuarioIdToAsiento")]
    partial class AddUsuarioIdToAsiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asientos.Dominio.Agregados.MapaAsientos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Mapas", (string)null);
                });

            modelBuilder.Entity("Asientos.Dominio.Entidades.Asiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Fila")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MapaAsientosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<bool>("Reservado")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MapaAsientosId");

                    b.HasIndex("MapaId", "Fila", "Numero")
                        .IsUnique();

                    b.ToTable("Asientos", (string)null);
                });

            modelBuilder.Entity("Asientos.Dominio.Agregados.MapaAsientos", b =>
                {
                    b.OwnsMany("Asientos.Dominio.ObjetosDeValor.CategoriaAsiento", "Categorias", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MapaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal?>("PrecioBase")
                                .HasColumnType("numeric");

                            b1.Property<bool>("TienePrioridad")
                                .HasColumnType("boolean");

                            b1.HasKey("Id");

                            b1.HasIndex("MapaId", "Nombre")
                                .IsUnique();

                            b1.ToTable("MapasCategorias", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MapaId");
                        });

                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Asientos.Dominio.Entidades.Asiento", b =>
                {
                    b.HasOne("Asientos.Dominio.Agregados.MapaAsientos", null)
                        .WithMany("Asientos")
                        .HasForeignKey("MapaAsientosId");

                    b.HasOne("Asientos.Dominio.Agregados.MapaAsientos", null)
                        .WithMany()
                        .HasForeignKey("MapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Asientos.Dominio.ObjetosDeValor.CategoriaAsiento", "Categoria", b1 =>
                        {
                            b1.Property<Guid>("AsientoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CategoriaNombre");

                            b1.Property<decimal?>("PrecioBase")
                                .HasColumnType("numeric")
                                .HasColumnName("CategoriaPrecioBase");

                            b1.Property<bool>("TienePrioridad")
                                .HasColumnType("boolean")
                                .HasColumnName("CategoriaTienePrioridad");

                            b1.HasKey("AsientoId");

                            b1.ToTable("Asientos");

                            b1.WithOwner()
                                .HasForeignKey("AsientoId");
                        });

                    b.Navigation("Categoria")
                        .IsRequired();
                });

            modelBuilder.Entity("Asientos.Dominio.Agregados.MapaAsientos", b =>
                {
                    b.Navigation("Asientos");
                });
#pragma warning restore 612, 618
        }
    }
}
