// <auto-generated />
using System;
using Entradas.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entradas.Infraestructura.Persistencia.Migrations
{
    [DbContext(typeof(EntradasDbContext))]
    [Migration("20260106024629_AgregarCamposSnapshot")]
    partial class AgregarCamposSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("entradas")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entradas.Dominio.Entidades.Entrada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AsientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("asiento_id");

                    b.Property<string>("CodigoQr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_qr");

                    b.Property<string>("CuponesAplicados")
                        .HasColumnType("jsonb")
                        .HasColumnName("cupones_aplicados");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("FechaActualizacion")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_compra");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaEvento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evento");

                    b.Property<string>("Fila")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("fila");

                    b.Property<string>("ImagenEventoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_evento_url");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_descuento");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_original");

                    b.Property<string>("NombreSector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_sector");

                    b.Property<int?>("NumeroAsiento")
                        .HasColumnType("integer")
                        .HasColumnName("numero_asiento");

                    b.Property<string>("TituloEvento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo_evento");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CodigoQr")
                        .IsUnique()
                        .HasDatabaseName("ix_entradas_codigo_qr");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_entradas_estado");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_entradas_evento_id");

                    b.HasIndex("FechaCompra")
                        .HasDatabaseName("ix_entradas_fecha_compra");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_entradas_usuario_id");

                    b.ToTable("entradas", "entradas", t =>
                        {
                            t.HasCheckConstraint("ck_entradas_estado_valido", "estado IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_entradas_monto_positivo", "monto > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
